# Site Information
title: ZZH
description: "Python开发工程师"
url: https://ZZH-0207.github.io
repo: ZZH-0207/ZZH-0207.github.io
lang: zh-CN
encoding: utf-8
timezone: Asia/Shanghai

# Social Media and External URLs
github: ZZH-0207
zhihu: -
menu:
  - title: "关于我"
    url: "/about.html"
  - title: "主页"
    url: "/categories.html"

# SEO and Analytics
google_analytics: G-KS7EDB6BRM

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed
